#!/bin/bash
#declare -i count=1
count1=0
cat $1 | while read LINE
cat $1 | while read LINE1

count1=`expr $count + 1`
echo $count1
then
else
fi
#echo $count
#!/bin/bash
#declare -i count=1
count1=0
cat $1 | while read LINE
cat $1 | while read LINE1

count1=`expr $count + 1`
done
if [ `expr $count % 2` = 0 ]
`echo $LINE >> evenfile`
`echo $LINE >> oddfile`
count=`expr $count + 1`
done
#!/bin/bash
#declare -i count=1
count1=0
cat $1 | while read LINE
cat $1 | while read LINE1

count1=`expr $count + 1`
done
if [ `expr $count % 2` = 0 ]
`echo $LINE >> evenfile`
`echo $LINE >> oddfile`
count=`expr $count + 1`
done
echo $count1
root:x:0:0:ashira,,,:/root:/bin/bash
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
